Numpy

Numpy is a fundamental library for scientific compution in python. It provides support for arrays along with a collection of mathematical function to operate on these data structures. In this lesson cover the basic of numpy, focusing on array and vectorized operations.

In [1]:
!pip install numpy


In [5]:
import numpy as np

## creating array by using numpy

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [ ]:
arr1=np.array([1,2,3,4,5])
arr1.reshape(1,5)  ## 1 row and 5 colums

array([[1, 2, 3, 4, 5]])

In [ ]:
## 1D array

arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2D array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,4]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 4]]
(2, 5)


In [ ]:
## single dimenction array into 2 dimension array
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attribuits of numpy array

arr=np.array([[1,2,3,4],[5,6,7,8]])

print("array:\n",arr)
print("shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("item size(in bytes):", arr.itemsize)

array:
 [[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
Number of dimensions: 2
size(number of elements): 8
Data type: int64
item size(in bytes): 8


In [2]:
## Numpy Vectorized Operation
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)

## Element wise Substarction
print("substraction:",arr1-arr2)

## Element wise Multiplication
print("Multiplication:",arr1*arr2)

## Element wise division
print("division:",arr1/arr2)

Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [3]:
## universal function

arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))
      
## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [6]:
## array slicing and Indexing

arr=np.array([[1,2,3,4,5],[6,7,8,1,9],[2,4,6,7,9,]])
print("Array: \n",arr)

Array: 
 [[1 2 3 4 5]
 [6 7 8 1 9]
 [2 4 6 7 9]]


In [8]:
arr[0][1]

np.int64(2)

In [11]:
arr[1:,2:]

array([[8, 1, 9],
       [6, 7, 9]])

In [14]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4 5]
 [8 1 9]]


In [16]:
print(arr[1:,1:3])

[[7 8]
 [4 6]]


In [17]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   1   9]
 [  2   4   6   7   9]]


In [19]:
arr[1:]=100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [20]:
## Statistical concept--- Normalization
## to have a mean of 0 and Standard deviation of 1

data=np.array([1,2,3,4,5,6])

#3 calculate the mean and standard deviation
mean=np.mean(data)
str_dev=np.std(data)

## Normalization the data
normalization_data=(data-mean)/str_dev
print("normalized data:",normalization_data)

normalized data: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Medion:",median)

# Mode
# mode = np.mode(data)
# print("mode:",mode)

# Standard Deviation
std_dev = np.std(data)
print("Standart deviation:",std_dev)

# Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Medion: 5.5
Standart deviation: 2.8722813232690143
Variance: 8.25


In [31]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])