Numpy

Numpy is a fundamental library for scientific compution in python. It provides support for arrays along with a collection of mathematical function to operate on these data structures. In this lesson cover the basic of numpy, focusing on array and vectorized operations.

In [1]:
!pip install numpy


In [5]:
import numpy as np

## creating array by using numpy

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [ ]:
arr1=np.array([1,2,3,4,5])
arr1.reshape(1,5)  ## 1 row and 5 colums

array([[1, 2, 3, 4, 5]])

In [ ]:
## 1D array

arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2D array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,4]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 4]]
(2, 5)


In [ ]:
## single dimenction array into 2 dimension array
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attribuits of numpy array

arr=np.array([[1,2,3,4],[5,6,7,8]])

print("array:\n",arr)
print("shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("item size(in bytes):", arr.itemsize)

array:
 [[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
Number of dimensions: 2
size(number of elements): 8
Data type: int64
item size(in bytes): 8


11
